### ISSUE TITLE
include sass in dev package or add info to readme how to install it

### ISSUE THREAD

**Issue by jaroslaw-weber** [ProfXwing/copytype#3]
my environment is quite clean so i was missing this package

```
 copytype % npm start

> copytype@1.0.4 start
> npm run build; concurrently -k npm:watch-ts-main npm:watch-ts-renderer npm:watch-sass npm:start-electron


> copytype@1.0.4 build
> tsc --project src/ts/main/tsconfig.json && tsc --project src/ts/renderer/tsconfig.json && sass src/styles:dist/styles

sh: sass: command not found
[watch-ts-main] 

```

maybe add info on how to install sass to readme or add it as dependency? currently not installing when running `npm i`

**Comment by ProfXwing** [comment]
Yeah, just me being stupid and installing globally it looks like. Let me try to add it to dev dependency

**Comment by ProfXwing** [comment]
Should be fixed on latest commit. Can you confirm on your end?

**Comment by jaroslaw-weber** [comment]
actually not sure cause i already installed globally :). but i think you can close ticket.

if it's still not working, sass can be installed from here: https://sass-lang.com/install/
