### ISSUE TITLE
make it possible to use without running locally

### ISSUE THREAD

**Issue by jaroslaw-weber** [ProfXwing/copytype#4]
i know hosting can cost, but if you use local storage and frontend only, it would be possible to host for free on github pages.

would greatly improve UX and let beginners with no coding experience use it right away

**Comment by jaroslaw-weber** [comment]
oh, sorry it's electron app. maybe you can build it and create a 'release' so its just download and click instead of running whole repo?

**Comment by ProfXwing** [comment]
I would love for copytype to be turned into a website eventually, but it's not feasible cost-wise, and I'm not a fan of the localstorage solution. Issues with clearing local storage etc would make me really mad as a user for my book to be cleaned, that's why storing in appdata and running locally is best solution. 

And yeah, it's written in electron so a rewrite would be in order to host it.

As for releases, good idea! https://github.com/ProfXwing/copytype/releases :)

**Comment by ProfXwing** [comment]
I unchecked pre-release so that built release shows up better in the repo and people don't get confused.

I still consider it a pre-release but I'm also not currently continuing development for the project, so that should make things better until I pick it up again

**Comment by jaroslaw-weber** [comment]
i think its fine like this :) . maybe good to mention it in readme?

btw im enjoying the tool, it's little buggy but it's free so cant complain. thanks.

**Comment by ProfXwing** [comment]
i'll add to readme

glad you're enjoying it. I think "a little buggy" is probably an understatement, and the code is far past spaghetti, but I started it with very little programming experience so I give myself some slack there. would love to take up the project again and make it good eventually, but school is all like "do this work" and I'm all like "no i don't want to"

**Comment by jaroslaw-weber** [comment]
it works so it's good enough :) 


i skimmed the code and seems you're using jquery. personally next time i'd go with something more modern like react (not sure if nextjs works with electron) or vue3 :) . jquery seems like hell to maintain.

anyway, good job :)

**Comment by ProfXwing** [comment]
Yeah, past me is always the worst programmer I know. I believe I chose jquery because monkeytype was written in jquery? not sure, but since I was basically rewriting most of monkeytype, I should've chose react because it is infinitely easier.

thanks again, enjoy
